name: Dizi
on:
  schedule:
    - cron: '0 0/3 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Get CennetMahallesi
      run: |
        touch ./dizi/cennetmahallesi.m3u8
        sudo cat >./dizi/cennetmahallesi.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@cennetmahallesishowtv/live)
        EOL

    - name: Get BehzatC
      run: |
        touch ./dizi/behzatc.m3u8
        sudo cat >./dizi/behzatc.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@Behzatc./live)
        EOL

    - name: Get YeniGelin
      run: |
        touch ./dizi/yenigelin.m3u8
        sudo cat >./dizi/yenigelin.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@yenigelindizi/live)
        EOL

    - name: Get SihirliAnnem
      run: |
        touch ./dizi/sihirliannem.m3u8
        sudo cat >./dizi/sihirliannem.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@SihirliAnnemDizi/live)
        EOL

    - name: Get EeeSonra
      run: |
        touch ./dizi/eeesonra.m3u8
        sudo cat >./dizi/eeesonra.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@EeeSonra/live)
        EOL

    - name: Get SefirinKizi
      run: |
        touch ./dizi/sefirinkizi.m3u8
        sudo cat >./dizi/sefirinkizi.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@sefirinkizidizi/live)
        EOL

    - name: Get Avlu
      run: |
        touch ./dizi/avlu.m3u8
        sudo cat >./dizi/avlu.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@avludizi/live)
        EOL

    - name: Get CilekKokusu
      run: |
        touch ./dizi/cilekkokusu.m3u8
        sudo cat >./dizi/cilekkokusu.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@CilekKokusu/live)
        EOL

    - name: Get FaziletHanim
      run: |
        touch ./dizi/fazilethanimvekizlari.m3u8
        sudo cat >./dizi/fazilethanimvekizlari.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@fazilethanimvekizlaridizi/live)
        EOL

    - name: Get HanimKoylu
      run: |
        touch ./dizi/hanimkoylu.m3u8
        sudo cat >./dizi/hanimkoylu.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@HanimKoyluDizi/live)
        EOL

    - name: Get HayatBazenTatlidir
      run: |
        touch ./dizi/hayatbazentatlidir.m3u8
        sudo cat >./dizi/hayatbazentatlidir.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@HayatBazenTatlidir/live)
        EOL

    - name: Get UfakTefekCinayerler
      run: |
        touch ./dizi/ufaktefekcinayetler.m3u8
        sudo cat >./dizi/ufaktefekcinayetler.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@ufaktefekcinayetlerdizi/live)
        EOL

    - name: Get IstanbulluGelin
      run: |
        touch ./dizi/istanbullugelin.m3u8
        sudo cat >./dizi/istanbullugelin.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@istanbullugelindizi/live)
        EOL        

    - name: git add
      run: |
        git add -A
        ls -la

    - name: commit & push
      run: |
        git commit -m "link are updated"
        git push
