name: Muzik
on:
  schedule:
    - cron: '0 0/3 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Get KralTV
      run: |
        touch ./muzik/kraltv.m3u8
        sudo cat >./dizi/kraltv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@kralmuzik/live)
        EOL

    - name: git add
      run: |
        git add -A
        ls -la

    - name: commit & push
      run: |
        git commit -m "link are updated"
        git push
