name: YouTube Live m3u8
on:
  schedule:
    - cron: '0 0/3 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Get beINSportsHaber
      run: |
        touch ./spor/beinsportshaber.m3u8
        sudo cat >./spor/beinsportshaber.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@beinsportsturkiye/live)
        EOL

    - name: Get ASpor
      run: |
        touch ./spor/aspor.m3u8
        sudo cat >./spor/aspor.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@ASpor/live)
        EOL

    - name: Get TayTv
      run: |
        touch ./spor/taytv.m3u8
        sudo cat >./spor/taytv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@TayTvOfficial/live)
        EOL

    - name: Get AHaber
      run: |
        touch ./haber/ahaber.m3u8
        sudo cat >./haber/ahaber.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/ahaber/live)
        EOL

    - name: Get APara
      run: |
        touch ./haber/apara.m3u8
        sudo cat >./haber/apara.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/channel/UCzrGg6iyRDuUSnO0cQ5oLcA/live)
        EOL

    - name: Get FilmAtolyesi
      run: |
        touch ./film/filmatolyesi.m3u8
        sudo cat >./film/filmatolyesi.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@filmatolyesi/live)
        EOL

    - name: Get KemalSunalTV
      run: |
        touch ./film/kemalsunaltv.m3u8
        sudo cat >./film/kemalsunaltv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@KemalSunalTV/live)
        EOL

    - name: Get KemalSunalFilmleri
      run: |
        touch ./film/kemalsunalfilmleri.m3u8
        sudo cat >./film/kemalsunalfilmleri.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@kemalsunalfilmleri/live)
        EOL

    - name: Get KemalSunalFilmleriveSahneleri
      run: |
        touch ./film/kemalsunalfilmlerivesahneleri.m3u8
        sudo cat >./film/kemalsunalfilmlerivesahneleri.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@KemalSunalFilmleriveSahneleri/live)
        EOL

    - name: Get Sirinler
      run: |
        touch ./cocuk/sirinler.m3u8
        sudo cat >./cocuk/sirinler.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@sirinler/live)
        EOL

    - name: Get ArzuFilm
      run: |
        touch ./film/arzufilm.m3u8
        sudo cat >./film/arzufilm.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@arzufilm1964/live)
        EOL

    - name: Get GulsahFilm
      run: |
        touch ./film/gulsahfilm.m3u8
        sudo cat >./film/gulsahfilm.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@GulsahFilmOfficial/live)
        EOL

    - name: Get CennetMahallesi
      run: |
        touch ./dizi/cennetmahallesi.m3u8
        sudo cat >./dizi/cennetmahallesi.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@cennetmahallesishowtv/live)
        EOL

    - name: Get TurkFimleriTV
      run: |
        touch ./film/turkfilmleri.m3u8
        sudo cat >./film/turkfilmleri.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@TurkFilmleri-TV/live)
        EOL

    - name: Get BehzatC
      run: |
        touch ./dizi/behzatc.m3u8
        sudo cat >./dizi/behzatc.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@Behzatc./live)
        EOL

    - name: Get KuzeyYildizi
      run: |
        touch ./dizi/kuzeyyildizi.m3u8
        sudo cat >./dizi/kuzeyyildizi.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@KuzeyYildiziDizi/live)
        EOL

    - name: Get MuratFilm
      run: |
        touch ./film/muratfilm.m3u8
        sudo cat >./film/muratfilm.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@MuratFilm/live)
        EOL

    - name: Get YeniGelin
      run: |
        touch ./dizi/yenigelin.m3u8
        sudo cat >./dizi/yenigelin.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@yenigelindizi/live)
        EOL

    - name: Get TurkFilmleri1onMedya
      run: |
        touch ./film/turkfilmleri1onmedya.m3u8
        sudo cat >./film/turkfilmleri1onmedya.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@1onmedya/live)
        EOL

    - name: Get SihirliAnnem
      run: |
        touch ./dizi/sihirliannem.m3u8
        sudo cat >./dizi/sihirliannem.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@SihirliAnnemDizi/live)
        EOL

    - name: Get EeeSonra
      run: |
        touch ./dizi/eeesonra.m3u8
        sudo cat >./dizi/eeesonra.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@EeeSonra/live)
        EOL

    - name: Get UfakTefekCinayerler
      run: |
        touch ./dizi/ufaktefekcinayetler.m3u8
        sudo cat >./dizi/ufaktefekcinayetler.m3u8
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@ufaktefekcinayetlerdizi/live)
        EOL

    - name: Get IstanbulluGelin
      run: |
        touch ./dizi/istanbullugelin.m3u8
        sudo cat >./dizi/istanbullugelin.m3u8
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@istanbullugelindizi/live)
        EOL

    - name: Get SefirinKizi
      run: |
        touch ./dizi/sefirinkizi.m3u8
        sudo cat >./dizi/sefirinkizi.m3u8
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@sefirinkizidizi/live)
        EOL

    - name: Get Dolunay
      run: |
        touch ./dizi/dolunay.m3u8
        sudo cat >./dizi/dolunay.m3u8
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@Dolunay/live)
        EOL

    - name: Get Avlu
      run: |
        touch ./dizi/avlu.m3u8
        sudo cat >./dizi/avlu.m3u8
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@avludizi/live)
        EOL

    - name: CilekKokusu
      run: |
        touch ./dizi/cilekkokusu.m3u8
        sudo cat >./dizi/cilekkokusu.m3u8
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@CilekKokusu/live)
        EOL

    - name: FaziletHanim
      run: |
        touch ./dizi/fazilethanimvekizlari.m3u8
        sudo cat >./dizi/fazilethanimvekizlari.m3u8
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@fazilethanimvekizlaridizi/live)
        EOL

    - name: HanimKoylu
      run: |
        touch ./dizi/hanimkoylu.m3u8
        sudo cat >./dizi/hanimkoylu.m3u8
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@HanimKoyluDizi/live)
        EOL

    - name: Get HayatBazenTatlidir
      run: |
        touch ./dizi/hayatbazentatlidir.m3u8
        sudo cat >./dizi/hayatbazentatlidir.m3u8
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@HayatBazenTatlidir/live)
        EOL

    - name: git add
      run: |
        git add -A
        ls -la

    - name: commit & push
      run: |
        git commit -m "links are updated"
        git push
